-- CreateTable
CREATE TABLE "Tabungan" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "jumlah" INTEGER NOT NULL DEFAULT 0,
    "tanggal" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "catatan" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
